export enum Province {
  GAUTENG = 'GAUTENG',
  EASTERN_CAPE = 'EASTERN CAPE',
  KWAZULU_NATAL = 'KWAZULU NATAL',
  FREE_STATE = 'FREE STATE',
  LIMPOPO = 'LIMPOPO',
  MPUMALANGA = 'MPUMALANGA',
  NORTH_WEST = 'NORTH WEST',
  NORTHERN_CAPE = 'NORTHERN CAPE',
  WESTERN_CAPE = 'WESTERN CAPE'
}