export enum Province {
  GAUTENG = 'GAUTENG',
  EASTERN_CAPE = 'EASTERN_CAPE',
  KWAZULU_NATAL = 'KWAZULU_NATAL',
  FREE_STATE = 'FREE_STATE',
  LIMPOPO = 'LIMPOPO',
  MPUMALANGA = 'MPUMALANGA',
  NORTH_WEST = 'NORTH_WEST',
  NORTHERN_CAPE = 'NORTHERN_CAPE',
  WESTERN_CAPE = 'WESTERN_CAPE'
}